list=['sydney', 'turkey', 'england', 'america']
print(list)
print(sorted(list))
print(list)
p=sorted(list)
p.reverse()
print(p)
print(list)
list.reverse()
print(list)
list.reverse()
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)