guest_list=['bill gates', 'mark zukerberg', 'andrew huberman']
print(f"hi {guest_list[0]} i'd like to invite you to dinner")
print(f"hi {guest_list[1]} i'd like to invite you to dinner")
print(f"hi {guest_list[2]} i'd like to invite you to dinner")
print("hey i just found bigger table for dinner")
guest_list.insert(0, 'yeri')
guest_list.insert(1, 'jasmine')
guest_list.append('maddie')
print(f"hi {guest_list[0]} i'd like to invite you to dinner")
print(f"hi {guest_list[1]} i'd like to invite you to dinner")
print(f"hi {guest_list[2]} i'd like to invite you to dinner")
print(f"hi {guest_list[3]} i'd like to invite you to dinner")
print(f"hi {guest_list[4]} i'd like to invite you to dinner")
print(f"hi {guest_list[5]} i'd like to invite you to dinner")