places=['eiffel tower', 'taj mahal' , 'statue of liberty', 'great wall of china', 'sydney opera house']
print(places)
print(sorted(places))
print(places)
p=sorted(places)
p.reverse()
print(p)
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)